---
apiVersion: v1
kind: Service
metadata:
  name: demo-kube-keycloak-react-frontend
spec:
  selector:
    app: demo-kube-keycloak-react-frontend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kube-keycloak-react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kube-keycloak-react-frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: demo-kube-keycloak-react-frontend
        track: stable
      name: demo-kube-keycloak-react-frontend
    spec:
      containers:
        - name: demo-kube-keycloak-react-frontend
          image: demo-kube-keycloak-react-frontend:2
          command: ["/bin/sh", "-c", "npm run build:prod && serve -s build"]
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
