apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-demo-react-frontend
spec:
  tls:
    - hosts:
        - FRONTEND_HOST
  rules:
    - host: FRONTEND_HOST
      http:
        paths:
          - backend:
              serviceName: kube-demo-react-frontend
              servicePort: 5000
